# Generated by Django 5.1.5 on 2025-11-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambiente',
            options={'verbose_name': 'Ambiente', 'verbose_name_plural': 'Ambientes'},
        ),
        migrations.AlterModelOptions(
            name='historico',
            options={'verbose_name': 'Histórico', 'verbose_name_plural': 'Históricos'},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name': 'Local', 'verbose_name_plural': 'Locais'},
        ),
        migrations.AlterModelOptions(
            name='responsavel',
            options={'verbose_name': 'Responsável', 'verbose_name_plural': 'Responsáveis'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensores'},
        ),
    ]
